name: cfc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.1.2
  rename: ^3.0.2
  url_launcher: ^6.3.1

  # Add any additional dependencies here
  # Example: provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/clearing.jpg
    - assets/images/cfc.jpg
    - assets/images/
    - assets/images/custom_duty.jpg
    - assets/images/Logistics.jpg

  