// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3QelBxBH8mT91isq6kAJnlUU6BVrlwA',
    appId: '1:535844648576:web:51d96f70bf7840f1d95865',
    messagingSenderId: '535844648576',
    projectId: 'cfcfreight-e3e7e',
    authDomain: 'cfcfreight-e3e7e.firebaseapp.com',
    storageBucket: 'cfcfreight-e3e7e.appspot.com',
    measurementId: 'G-KCDLX80BTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU4Mm4wP0pB1_8e_d-tBEEdr1vn9TgvsY',
    appId: '1:535844648576:android:9c8af5f03cd5f41ed95865',
    messagingSenderId: '535844648576',
    projectId: 'cfcfreight-e3e7e',
    storageBucket: 'cfcfreight-e3e7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5v8J1EylnFYDdAH7RkqdHx0FU0sj5qdw',
    appId: '1:535844648576:ios:e93266823afcf66fd95865',
    messagingSenderId: '535844648576',
    projectId: 'cfcfreight-e3e7e',
    storageBucket: 'cfcfreight-e3e7e.appspot.com',
    iosBundleId: 'com.example.flutterNodeAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5v8J1EylnFYDdAH7RkqdHx0FU0sj5qdw',
    appId: '1:535844648576:ios:e93266823afcf66fd95865',
    messagingSenderId: '535844648576',
    projectId: 'cfcfreight-e3e7e',
    storageBucket: 'cfcfreight-e3e7e.appspot.com',
    iosBundleId: 'com.example.flutterNodeAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3QelBxBH8mT91isq6kAJnlUU6BVrlwA',
    appId: '1:535844648576:web:507b369e37461810d95865',
    messagingSenderId: '535844648576',
    projectId: 'cfcfreight-e3e7e',
    authDomain: 'cfcfreight-e3e7e.firebaseapp.com',
    storageBucket: 'cfcfreight-e3e7e.appspot.com',
    measurementId: 'G-J3H1PXX86J',
  );
}
